# Generated by Django 5.0.1 on 2024-01-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_settings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_blok1', models.CharField(max_length=155, verbose_name='Заголовок блока1')),
                ('title_blok2', models.CharField(max_length=155, verbose_name='Заголовок блока2')),
                ('title_blok3', models.CharField(max_length=155, verbose_name='Заголовок блока3')),
                ('description_blok1', models.TextField(verbose_name='Описание блока1')),
                ('description_blok2', models.TextField(verbose_name='Описание блока2')),
                ('description_blok3', models.TextField(verbose_name='Описание блока3')),
            ],
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={},
        ),
    ]
