# Generated by Django 5.0.1 on 2024-01-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_blok_alter_settings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blok',
            name='title_description_blok1',
            field=models.CharField(max_length=2, null=True, verbose_name='Надпис после заголовок блока1'),
        ),
        migrations.AddField(
            model_name='blok',
            name='title_description_blok2',
            field=models.CharField(max_length=2, null=True, verbose_name='Надпис после заголовок блока2'),
        ),
        migrations.AddField(
            model_name='blok',
            name='title_description_blok3',
            field=models.CharField(max_length=2, null=True, verbose_name='Надпис после заголовок блока3'),
        ),
    ]
