# Generated by Django 5.0.1 on 2024-01-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_blok_title_description_blok1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blok',
            name='title_description_blok1',
            field=models.CharField(default='m', max_length=2, verbose_name='Надпис после заголовок блока1'),
        ),
        migrations.AlterField(
            model_name='blok',
            name='title_description_blok2',
            field=models.CharField(default='m', max_length=2, verbose_name='Надпис после заголовок блока2'),
        ),
        migrations.AlterField(
            model_name='blok',
            name='title_description_blok3',
            field=models.CharField(default='m', max_length=2, verbose_name='Надпис после заголовок блока3'),
        ),
    ]
