# Generated by Django 5.0.1 on 2024-01-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_blok_title_description_blok1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blok_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок блока')),
                ('title1', models.CharField(max_length=155, verbose_name='Заголовок Текста')),
                ('title2', models.CharField(max_length=155, verbose_name='Заголовок второго текста')),
                ('title3', models.CharField(max_length=155, verbose_name='Заголовок третего текста')),
                ('description', models.TextField(verbose_name='Описание третего текста')),
                ('image', models.ImageField(upload_to='portrait/', verbose_name='Фотография')),
            ],
        ),
    ]
