# Generated by Django 5.0.1 on 2024-01-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_blok_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blok_area',
            name='image',
            field=models.ImageField(upload_to='portrait/', verbose_name='Фотография блока'),
        ),
    ]
