# Generated by Django 5.0.1 on 2024-01-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_blok_area_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blok_Area',
        ),
    ]
