# Generated by Django 5.0.1 on 2024-01-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_blok_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blok_Area',
        ),
    ]
